esphome:
  name: aux-lab-solder-lights

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "1p9g3ru3dKGS5oAVVtbufZLqqXmKnzc/7c4LBb0A1eo="

ota:
  password: "cff30f9b166a6a889655f03fc1baf0a1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Aux-Lab-Solder-Lights"
    password: "aiIwPu43h6eE"

captive_portal:


switch:
  - platform: gpio
    name: "Solder Lamp 1"
    pin: 5
    inverted: false
    
  - platform: gpio
    name: "Solder Lamp 2"
    pin: 17
    inverted: true
  
  - platform: gpio
    name: "Solder Lamp 3"
    pin: 16
    inverted: true
  
  - platform: gpio
    name: "Solder Lamp 4"
    pin: 4
    inverted: true
