esphome:
  name: aux-lab-fan-back
  includes:
    - ifan02.h  
esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "ENoFqdcypRyoHM2r9qKZ7eWRunUqQ5jYXWPajGMoa3E="

ota:
  password: "2d90313e6a1070320bab5aeb96d742ec"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Aux-Lab-Fan-Back"
    password: "uAAAZx4uxfOp"

captive_portal:

output:
  - platform: custom
    type: float
    outputs:
      id: fanoutput
    lambda: |-
      auto ifan02_fan = new IFan02Output();
      App.register_component(ifan02_fan);
      return {ifan02_fan};

 
switch:
  - platform: template
    id: update_fan_speed
    optimistic: true
    turn_on_action:
      then:
        - delay: 200ms
        - if:
            condition:
              and:
                - switch.is_off: fan_relay1
                - switch.is_off: fan_relay2
               
            then:
              - fan.turn_off: ifan02_fan
        - if:
            condition:
              and:
                - switch.is_on: fan_relay1
                - switch.is_off: fan_relay2
               
            then:
              - fan.turn_on:
                  id: ifan02_fan
                  speed: 1
        - if:
            condition:
              and:
                - switch.is_off: fan_relay1
                - switch.is_on: fan_relay2
               
            then:
              - fan.turn_on:
                  id: ifan02_fan
                  speed: 2
        - if:
            condition:
              and:
                - switch.is_on: fan_relay1
                - switch.is_on: fan_relay2
            then:
              - fan.turn_on:
                  id: ifan02_fan
                  speed: 3
        - switch.turn_off: update_fan_speed

  - platform: gpio
    pin: GPIO14
    id: fan_relay1

  - platform: gpio
    pin: GPIO25
    id: fan_relay2


fan:
  - platform: speed
    output: fanoutput
    id: ifan02_fan
    speed_count: 3
    name: "iFan02 Fan"