esphome:
  name: aux-lab

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "JSseGSUZAcPTJ8xPIu6DdmmkfREaPqh/lUpqrtPxqLg="

ota:
  password: "3c0cc18de253a300296ca98f16bc655d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #manual_ip:
  #  static_ip: 192.168.0.246
  #  gateway: 192.168.0.1
  #  subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Aux-Lab Fallback Hotspot"
    password: "paclingaf"

captive_portal:

switch:
  - platform: gpio
    name: "Light mini"
    pin: 19
    inverted: true
    
  - platform: gpio
    name: "Light back"
    pin: 18
  
  - platform: gpio
    name: "Fan back"
    pin: 5
  
  - platform: gpio
    name: "Light front"
    pin: 16
  
  - platform: gpio
    name: "Fan front"
    pin: 17
output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: 12
    zero_cross_pin:
      number: 14
      mode:
        input: true
    max_power: 90%

light:
  - platform: monochromatic
    output: dimmer1
    name: Dimmerized Light
    default_transition_length: 50ms

