esphome:
  name: main-lab

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "k7SOiznXGD4MN5C3/wRQ+KkLvYIZnWW3P2npnijoQdA="

ota:
  password: "487afda696af6316cbc8926ecc1999fd"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Main-Lab Fallback Hotspot"
    password: "S5DbYR7vnHrL"

captive_portal:
  
switch:
  - platform: gpio
    name: "Light mini"
    pin: 19
    inverted: false
    
  - platform: gpio
    name: "Light back"
    pin: 18
    inverted: true
  
  - platform: gpio
    name: "Fan back"
    pin: 5
    inverted: true
  
  - platform: gpio
    name: "Light front"
    pin: 16
    inverted: true
  
  - platform: gpio
    name: "Fan front"
    pin: 17
    inverted: true