name: Update Lamp
on:
  push:
    branches:    
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Restart Service
      run: sudo systemctl restart epaper.service

